var GAME_LEVELS = [
	["      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                           ",
	 "      x oooo ooooo  oo  ooo   ooooo x                           ",
	 "        o      o   o  o o  o    o                               ",
	 "        oooo   o   oooo ooo     o                               ",
	 "           o   o   o  o o  o    o                               ",
	 "        oooo   o   o  o o   o   o                               ",
	 "      x                            ex                           ",
	 "      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxx             ",
	 "    @ x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxx    |     |     o     ",
	 "xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxx"],
	["                                                                     ",
	 "                                                                     ",
	 "             xxxx                                                    ",
	 "            x!!!!x                                                   ",
	 "           x!!||!!x                                                  ",
	 "           x!!  !!x                                                  ",
	 "           x|    |x                                                  ",
     "                                                                     ",
	 "             o o                                                     ",      
	 "                                  oo         xxxx                    ",
	 "                                             x!!x                    ",
	 "                                xxxxxx    o  x!!x                    ",
	 "         xxx      xxx           x    x    o  x!!x                    ",
	 "                            xxxxx    x    o  x!!xxx                  ",
	 "   @                        x        x    o  x!!!!x          o o o o ",
	 "xxxxxxxx                xxxxx        xxx  o  x!!!!xxxxxxxxxxxxxxxxxxx",
	 "       x!!!!!!!!!!!!!!!!x              x  o  x!!!!!!!!!!!!!!!!!!!!!!x",
	 "       xxxxxxxxxxxxxxxxxx              x ooo xxxxxxxxxxxxxxxxxxxxxxxx",
	 "                                       x  o                         x",
	 "                                       x e                         ox",
	 "                                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
	["                                ",
	 "                                ",
	 "                                ",
	 "                                ",  
	 "                                ",
	 "                                ",
   	 "                                ",                                    
	 "   xxx                          ",
	 "  x!|!x                      o  ",
	 "  x                        xxxxx",
	 "  x               xxxx     x    ",
	 "  x                        x    ",
	 "  x   xxxxxxxxx            x    ", 
	 "  x   x!|!x!|!x            x    ",
	 "  x                        x    ",
	 "  x                        x    ",
	 "  xxxxxxxxxxxxx            x    ",
	 "                           x    ",   
	 "                           x    ",
	 "                   o       x    ",
	 "                           x    ",
	 "                  xxx      x    ",
	 "                           xxxxx",
	 "                           !!!!x",
	 "                        xxxxxxxx",
	 "                           x    ",             
	 "                           x    ",
	 "                   o       x    ",
	 "                           x    ",
     "                  xxx      x    ",
     "                           x    ",
     "                           x    ",
     "                           xxxxx",
     "                           !!!!x",
     "                        xxxxxxxx",
     "                           x    ",
     "      o                    x    ",
     "     xxx                   x    ",
     "     x         xxxxxxxxxxxxx    ",
     "     x        ex                ",
     "     x       xxx                ", 
     "     x    o    x                ",
     "     x         x                ",
     "     xxx       x                ",
     "     x         x                ",
     "     xe        x                ",
     "     x       xxx                ",
     "     x    o    x                ",
     "     x         x                ",
     "     xxx       x                ",
     "     x         x                ",
     "     x        ex                ",
     "     x       xxx                ",
     "     x    o    x                ",
     "     x         x                ",
     "     xxx       x                ",
     "     x         x                ", 
     "     xe        x                ",
     "xxxxxx       xxx                ",
     "               x                ",
	 "  @            x                ",
	 "xxxxxxxxxxxxxxxx                "],
	["      xx!xxxxxxx!xxxxxxxxx!xxxxxxx!xx                   ",
	 "      x v ooooo voo     o v ooo   v x                   ",
	 "          o      o o    o   o  o                        ",
	 "          ooooo  o  o   o   o   o                       ",
	 "          o      o   o  o   o   o                       ",
	 "          ooooo  o     oo   oooo                        ",
	 "      xee e    e       e       e  eex            o      ",
	 "      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx e         xxx     ",
	 "    @ x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxx  |  |     | |",
	 "xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"]
];
if (typeof module != "undefined" && module.exports)
module.exports = GAME_LEVELS;